# Golang CircleCI 2.0 configuration file
# See https://circleci.com/docs/2.0/language-go/
version: 2.1
jobs:
  build:
    working_directory: /home/circleci/zigmod
    docker:
      - image: alpine:edge
    steps:
      - run: apk update
      - run: apk add git
      - checkout
      - run: git submodule update --init --recursive

      - run: apk add go
      - run: go version
      - run: go env
      - run: go get -v .
      - run: go test -v .
      - run: ./build_all.sh
      - store_artifacts:
          path: ./bin/
          destination: /artifacts/

      - run: ./download_zig.sh 0.7.0
      - run: zig version
      - run: zig env
      - run: apk add jq grep
      - run: ./build_all_zig.sh
      - store_artifacts:
          path: ./zig-cache/bin/
          destination: /artifacts/

      - run: ./make_release.sh
