# Golang CircleCI 2.0 configuration file
# See https://circleci.com/docs/2.0/language-go/
version: 2.1
jobs:
  build:
    working_directory: /home/circleci/zigmod
    docker:
      - image: golang
    environment:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - run: apt update
      - run: apt -y upgrade
      - checkout
      - run: git submodule update --init --recursive

      - run: go version
      - run: go env
      - run: go get -v .
      - run: go test -v .
      - run: ./build_all.sh
      - store_artifacts:
          path: ./bin/
          destination: /artifacts/

      - run: apt -y install xz-utils jq
      - run: ./download_zig.sh 0.7.0
      - run: zig version
      - run: zig env
      - run: ./build_all_zig.sh
      - store_artifacts:
          path: ./zig-cache/bin/
          destination: /artifacts/

      - run: mkdir -p /artifacts/
      - run: cp -R ./bin/. /artifacts/
      - run: cp -R ./zig-cache/bin/. /artifacts/
      - run: ./make_release.sh
