name: CI

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: "recursive"
      - run: git fetch --all --tags
      - run: top -b -n 1 | head -n5

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: "0.12.0"

      - run: zig version
      - run: zig env
      - run: zig build -j1

      # Build All
      - run: ./build_release.sh x86_64-linux-musl
      - run: ./build_release.sh x86_64-macos-none
      - run: ./build_release.sh x86_64-windows-gnu
      - run: ./build_release.sh aarch64-linux-musl
      - run: ./build_release.sh aarch64-macos-none
      - run: ./build_release.sh aarch64-windows-gnu
      - run: ./build_release.sh riscv64-linux-musl
      - run: ./build_release.sh powerpc64le-linux-musl
      - run: ./build_release.sh mips64-linux-musl

      # Test
      - run: ./zig-out/bin/zigmod version
      - run: ./zig-out/bin/zigmod zpm add apple_pie
      - run: ./zig-out/bin/zigmod zpm tags
      - run: ./zig-out/bin/zigmod aq add 1/vrischmann/sqlite

      - run: ./test_repo.sh https://github.com/nektro/zigmod-test-basic
      - run: ./test_repo.sh https://github.com/nektro/zigmod-test-git-dep
      - run: ./test_repo.sh https://github.com/nektro/zigmod-test-hg-dep
      - run: ./test_repo.sh https://github.com/nektro/zigmod-test-http-dep

      # Github Release
      - run: ./changelog.sh
      - run: ./make_release.sh ${{ secrets.GITHUB_TOKEN }}
