name: CI

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: "recursive"
      - run: git fetch --all --tags
      - run: top -b -n 1 | head -n5

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: "0.10.0-dev.531+3eb8d01f5"

      - run: zig version
      - run: zig env
      - run: zig build -Dbootstrap
      - run: ./zig-out/bin/zigmod ci
      - run: cat deps.zig
      - run: zig build

      # Build All
      - run: ./build_release.sh aarch64-linux-musl
      - run: ./build_release.sh aarch64-macos-gnu
      - run: ./build_release.sh aarch64-windows-gnu
      - run: ./build_release.sh i386-linux-musl
      - run: ./build_release.sh x86_64-linux-musl
      - run: ./build_release.sh x86_64-macos-gnu
      - run: ./build_release.sh x86_64-windows-gnu

      # Github Release
      - run: ./changelog.sh
      - run: ./make_release.sh ${{ secrets.GITHUB_TOKEN }}
